user_pref("extensions.zotero.openURL.name", "University of Twente");
user_pref("extensions.zotero.openURL.resolver", "https://ut.on.worldcat.org/atoztitles/link/");
user_pref("bidi.browser.ui", true);
user_pref("browser.theme.toolbar-theme", 1);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"zoteroAddons@ytshen.com\":\"6bf0e2e0-0421-4fad-b788-a87b1df16d38\",\"better-bibtex@iris-advies.com\":\"90927c26-f4da-403b-ab61-90a447cab22f\",\"zoteroshortdoi@wiernik.org\":\"851613f5-6fc7-44a3-a3d2-32cff67afbdc\",\"zoteroattanger@polygon.org\":\"8740095f-6b0f-4db3-b7ef-4cf30ec91393\",\"zotero-format-metadata@northword.cn\":\"a4962b96-8a32-43ca-ab4c-450a72dde228\",\"zoplicate@chenglongma.com\":\"f3971718-e19c-4a77-83e9-454a802c47b0\",\"reading-list@hotmail.com\":\"12c80ef8-8899-48ef-84b6-032d1e2f1468\",\"zotmeta@roadtodream.tech\":\"6d0ca8da-4b3d-475b-938b-18f5e9d6f044\",\"zotero-plugin@inciteful.xyz\":\"f351322d-3e57-4395-8586-54df4650ab02\"}");
user_pref("extensions.zotero.dataDir", "ROOTPATH\\Data\\profile");
user_pref("extensions.zotero.duplicateLibraries", "{}");
user_pref("extensions.zotero.export.lastLocale", "en-US");
user_pref("extensions.zotero.export.noteQuickCopy.setting", "{\"mode\":\"export\",\"id\":\"a45eca67-1ee8-45e5-b4c6-23fb8a852873\",\"markdownOptions\":{\"includeAppLinks\":true},\"htmlOptions\":{\"includeAppLinks\":true}}");
user_pref("extensions.zotero.export.quickCopy.setting", "export=b6e39b57-8942-4d11-8259-342c46ce395f");
user_pref("extensions.zotero.fontSize", "0.92");
user_pref("extensions.zotero.formatmetadata.cleanExtra", true);
user_pref("extensions.zotero.formatmetadata.lint.onGroup", true);
user_pref("extensions.zotero.formatmetadata.version", "1.18.4");
user_pref("extensions.zotero.httpServer.localAPI.enabled", true);
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"false\",\"width\":\"240\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-collections-pane\":{\"width\":\"92\"}}");
user_pref("extensions.zotero.panes.better-bibtex-iris-advies-com-betterbibtex-section-citationkey.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.zoplicate-chenglongma-com-sec-non-duplicates.open", true);
user_pref("extensions.zotero.panes.zoterotldr-syt-com-zoterotldr.open", true);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"P1\":false}");
user_pref("extensions.zotero.sync.reminder.setUp.enabled", false);
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1725215686);
user_pref("extensions.zotero.uiDensity", "compact");
user_pref("extensions.zotero.zoplicate.bulk.master.item", "detailed");
user_pref("extensions.zotero.zoplicate.duplicate.default.action", "discard");
user_pref("extensions.zotero.zotero-reading-list.enable-keyboard-shortcuts", false);
user_pref("extensions.zotero.zotero-reading-list.label-items-when-opening-file", true);
user_pref("extensions.zotero.zotero-reading-list.label-new-items", "New");
user_pref("extensions.zotero.zotero-reading-list.read-status-format", 0);
user_pref("extensions.zotero.zotero-reading-list.readstatuscolumn-format-header-showicon", true);
user_pref("extensions.zotero.zotero-reading-list.status-change-on-open-item-list", "New;To Read;Ignore|In Progress;In Progress;In Progress");
user_pref("extensions.zotero.zotero-reading-list.statuses-and-icons-list", "New;To Read;In Progress;Read;Ignore|⭐;📙;📖;📗;📕");
user_pref("extensions.zotero.zoteroaddons.autoUpdate", true);
user_pref("extensions.zotero.zoteroaddons.checkUncompatibleAddonsIn7", true);
user_pref("extensions.zotero.zoteroaddons.firstInstalledVersion", "1.0.0");
user_pref("extensions.zotero.zoteroaddons.guideStatus", 1);
user_pref("extensions.zotero.zoteroaddons.source", "source-zotero-chinese-gitee");
user_pref("extensions.zotero.zoteroaddonscolumns", "[{\"dataKey\":\"menu-name\",\"label\":\"Name\",\"staticWidth\":true,\"hidden\":false,\"originalMinWidth\":20,\"ordinal\":0,\"flex\":1,\"width\":193.5},{\"dataKey\":\"menu-desc\",\"label\":\"Description\",\"fixedWidth\":false,\"hidden\":false,\"ordinal\":1,\"flex\":1,\"width\":274.5},{\"dataKey\":\"menu-star\",\"label\":\"⭐️\",\"staticWidth\":true,\"width\":98.5,\"hidden\":false,\"originalMinWidth\":20,\"ordinal\":2},{\"dataKey\":\"menu-remote-update-time\",\"label\":\"Release time\",\"staticWidth\":true,\"width\":87.5,\"hidden\":false,\"originalMinWidth\":20,\"ordinal\":3},{\"dataKey\":\"menu-remote-version\",\"label\":\"Latest version\",\"staticWidth\":true,\"width\":100,\"hidden\":false,\"originalMinWidth\":20,\"ordinal\":4},{\"dataKey\":\"menu-local-version\",\"label\":\"Local version\",\"staticWidth\":true,\"width\":85,\"hidden\":false,\"originalMinWidth\":20,\"ordinal\":5},{\"dataKey\":\"menu-install-state\",\"label\":\"Local status\",\"staticWidth\":true,\"width\":95,\"hidden\":false,\"originalMinWidth\":20,\"ordinal\":6}]");
user_pref("extensions.zotero.zoteroattanger.destDir", "ROOTPATH\\_example_cloud_folder");
user_pref("extensions.zotero.zoteroattanger.sourceDir", "ROOTPATH\\Pdfs");
user_pref("zotero.addons.ui", "[\"columns\"]");
user_pref("extensions.zotero.translators.better-bibtex.asciiBibLaTeX", true);
user_pref("extensions.zotero.translators.better-bibtex.auxImport", true);
user_pref("extensions.zotero.translators.better-bibtex.bibtexParticleNoOp", true);
user_pref("extensions.zotero.translators.better-bibtex.bibtexURL", "note-url-ish");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.keyScope", "global");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "C:\\Program Files\\Git\\cmd\\git.EXE");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "win");
user_pref("extensions.zotero.translators.better-bibtex.qualityReport", true);
